FROM nginx:alpine

# Copy nginx configuration
COPY nginx.docker.conf /etc/nginx/conf.d/default.conf

# Create nginx directories
RUN mkdir -p /usr/share/nginx/html

# Expose port
EXPOSE 8091

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
